### ISSUE TITLE
error on raven pulse

### ISSUE THREAD

**Issue by ratacat** [ratacat/enceladusgame#33]
```
Caused: TypeError: this.metadata.attacks[id] is not iterable
    at Fight._doPulse (/Users/jared/Dev/enceladus/bundles/enceladus-new-combat/lib/Fight.js:281:44)
    at Fight.checkPulse (/Users/jared/Dev/enceladus/bundles/enceladus-new-combat/lib/Fight.js:90:32)
    at Function.updateRound (/Users/jared/Dev/enceladus/bundles/enceladus-new-combat/lib/Combat.js:54:54)
    at Player.<anonymous> (/Users/jared/Dev/enceladus/bundles/enceladus-new-combat/player-events.js:40:23)
    at Player.emit (events.js:203:15)
    at Player.emit (/Users/jared/Dev/core/src/EffectableEntity.js:29:11)
    at Player.emit (/Users/jared/Dev/core/src/Player.js:67:11)
    at PlayerManager.tickAll (/Users/jared/Dev/core/src/PlayerManager.js:188:14)
    at PlayerManager.emit (events.js:198:13)
    at Timeout.setInterval [as _onTimeout] (/Users/jared/Dev/enceladus/ranvier:172:28)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
```

**Comment by ratacat** [comment]
I think this is fixed
